### PR TITLE
New Text Helper

### PR DESCRIPTION
**Pull request by jacklightbody**
added a new text helper with options to camelCase, snake_case, and strip tags.

### CODE REVIEW

**Comment by bauffman** [comment]
What you're actually suggesting is that Filter is now used for more than filtering alone and a 'text' component should be nice to bundle methods used to modify strings, right?

**Comment by jacklightbody** [comment]
yeah, I guess so- I hadn't even realized filter had some text specific functions until you directed my attention to it though, so even just changing its name I think would be helpful fo people new to the system.

**Comment by davelens** [comment]
Filter as it is now is a generic bin for sanitizing/validating input, text manipulation and array-related methods, so you raise a valid point. It makes sense to split into a Text and Array component.

**Comment by bauffman** [comment]
In the new components this has been added as a separate component. Thanks for pointing this out!

**Comment by jacklightbody** [comment]
great!

**Pull request closed without merging**
