### PR TITLE
SpoonDropdown: normal values and option groups can now be combined in one

### PR DESCRIPTION
**Pull request by vanbosse**
SpoonDropdown: normal values and option groups can now be combined in one dropdown
Unit tests included!

### CODE REVIEW

**Comment by bauffman** [comment]
Did you actually try to run the unit tests for SpoonFormDropdown? I get the following results:

http://www.spoon-library.be/screenshots/2011-09-23-21-34-31.png

**Comment by vanbosse** [comment]
Well, that's kinda odd, these are my results.
http://cl.ly/1g1W0H46450X3p2R1k2B

**Comment by jelmersnoeck** [comment]
I'm getting the error as well. Though, it is easily fixed by replacing line 311 with:

```
if(isset($this->optionGroups[$this->selected])) $values = $data[$this->attributes['name']];
```

Before/after:
http://www.imgdumper.nl/uploads4/4e7dbbd542347/4e7dbbd540018-Screen_shot_2011-09-24_at_13.14.20.png

**Comment by vanbosse** [comment]
Fixed in last request. I guess I might take a look at my PHPUnit than...

**Pull request merged**
