### PR TITLE
SpoonDatabase & SpoonFormHidden

### PR DESCRIPTION
**Pull request by iweindesmedt**
1. There was no database getter yet, I think it would be interesting to have one.
2. When serializing a SpoonDatabase object with an initialized handler, an error gets thrown because PDO objects cannot be serialized. I suggest the implementation of __sleep(), allowing a SpoonDatabase object to get serialized.
3. An attempt to fix HTML validation for SpoonFormHidden.

(!) I accidently left 'return $this->driver;' instead of 'return $this->database;' in getDatabase() >.<

### CODE REVIEW

**Comment by janmoesen** [comment]
"Parsing into" is dubious Spoon/Fork lingo, and should be avoided. Not that you are to blame, obviously. :-)

That said, are you familiar with `$form->getTemplateExample()` for SpoonForm instances? Rather useful when you are creating templates. It includes the hidden UTF-8 detection and the form token inputs.

As for the difference between DIV and P: semantics. A DIV is meant to convey no special meaning, whereas a P is a paragraph. (In that case, you might argue that using a DIV just to shut up the HTML 4/XHTML 1 validator is a workaround at best.)

**Comment by janmoesen** [comment]
Of course, `getTemplateExample()` still does not wrap the hidden inputs in DIVs, but at least you can easily copy-paste them into your actual template.

**Comment by bauffman** [comment]
You can change your pull request to fix the $this->driver issue instead of $this->database. Also note that methods should be placed in alphabetical order. Magic methods such as __sleep can be placed after the __construct, __destruct method.

As for the FormHidden element I'd suggest a meaningless div as Jan suggest.

**Comment by janmoesen** [comment]
For the record: I did not mean to push the DIV wrapper as the solution. In fact, quite the contrary: I would leave it up to the templater. (S/he can then put multiple hidden inputs in a single DIV, or use HTML5 and skip the silly wrapper entirely.)

**Comment by iweindesmedt** [comment]
So you are saying that the templater should tell the developer to adjust the output of SpoonFormHidden fields to fit his needs?
Maybe I didn't make it clear enough, but the actual problem I have with the hidden field is that 1 hidden field gets automatically created in the template without the templater knowing. And thats where the invalid XHTML comes in.

AFAIK, the only way its HTML wrapping can be adjusted is through editing the SpoonFormHidden code... So I suggest not to let that field automatically create, so the templater can indeed choose how its being displayed.

Should I revert the changes I made to SpoonFormHidden and leave this open to discussion?

**Comment by janmoesen** [comment]
My bad, I was unaware of the automagically added fields. So basically, it's a trade-off: by automagically adding the DIV wrapper, it ensures HTML 4/XHTML 1 compatibility at the expense of an unnecessary element for HTML5 documents.

I do not know what the Spoon/Fork developers prefer, so I'll simply defer to them.

**Pull request closed without merging**
