### PR TITLE
Spoon: make the exception handler more usable

### PR DESCRIPTION
**Pull request by janmoesen**
- Separate the stack entries
- Show the stack trace before the superglobals
- Link to PHP/Spoon class and function documentation (with Google's best guess)
- Only show the superglobals that are not empty
- Visually indicate empty referrers and user agents
- Use word break hints instead of hard line breaks for long paths
- Dim the common path prefix so the relevant part of the source file's path stands out

Note that this is still bile solidified as code, but it is at least slightly
better. Now if only someone would unfuck the wretched tag soup that is its
output…

This is a big ol' commit instead of atomic changes. My appy polly loggies.

### CODE REVIEW

**Comment by bauffman** [comment]
When there are no superglobals that contain values, you get something that looks like this.
http://www.spoon-library.be/screenshots/2011-09-23-15-05-12.png

I do like the explicit 'there is no trace' message, but I'd rather not see the superglobals block if there are none.

**Comment by janmoesen** [comment]
Good catch. I had added `$_SERVER` first, which is always there. I can either add it back, or leave out the entire block `if empty($_GET) && empty($_POST)` … Your pick.

**Comment by bauffman** [comment]
I'd leave it the way it is, but place an if condition at https://github.com/janmoesen/spoon/blob/improve-exception-handler/spoon/exception/exception.php#L290

That way the block won't be shown if there are no variables that actually contain something.

Why would you want to add $_SERVER btw if you're working hard to remove everything that doesn't provide any helpfull exception feedback?

**Comment by janmoesen** [comment]
> Why would you want to add $_SERVER btw if you're working hard to remove everything that doesn't provide any helpfull exception feedback?

HTTP headers, environment (`$_ENV` would work, too, of course), server and network information, …

Anyway, don't worry: I left them out.

**Pull request merged**
